import type {
  Sector,
  Member,
  Event,
  Leadership,
  Partner,
  SiteSettings,
} from './types'

// ─── Sectors ────────────────────────────────────────────────────────────────

export const mockSectors: Sector[] = [
  {
    _id: 'sector-1',
    _type: 'sector',
    name: 'Healthcare',
    slug: { current: 'healthcare' },
    icon: 'Stethoscope',
    description: 'Medical practices, clinics, pharmacies, and healthcare technology providers serving the Central Valley.',
    order: 1,
  },
  {
    _id: 'sector-2',
    _type: 'sector',
    name: 'Real Estate',
    slug: { current: 'real-estate' },
    icon: 'Building2',
    description: 'Residential and commercial real estate developers, brokers, and property management firms.',
    order: 2,
  },
  {
    _id: 'sector-3',
    _type: 'sector',
    name: 'Legal',
    slug: { current: 'legal' },
    icon: 'Scale',
    description: 'Law firms and legal professionals specializing in immigration, business, and family law.',
    order: 3,
  },
  {
    _id: 'sector-4',
    _type: 'sector',
    name: 'Technology',
    slug: { current: 'technology' },
    icon: 'Code2',
    description: 'Software development, IT consulting, and technology solutions for businesses of all sizes.',
    order: 4,
  },
  {
    _id: 'sector-5',
    _type: 'sector',
    name: 'Hospitality',
    slug: { current: 'hospitality' },
    icon: 'UtensilsCrossed',
    description: 'Hotels, restaurants, catering services, and event venues across the Valley.',
    order: 5,
  },
  {
    _id: 'sector-6',
    _type: 'sector',
    name: 'Agriculture',
    slug: { current: 'agriculture' },
    icon: 'Wheat',
    description: 'Farming operations, food processing, agricultural technology, and supply chain management.',
    order: 6,
  },
  {
    _id: 'sector-7',
    _type: 'sector',
    name: 'Education',
    slug: { current: 'education' },
    icon: 'GraduationCap',
    description: 'Tutoring centers, test preparation, educational technology, and training academies.',
    order: 7,
  },
  {
    _id: 'sector-8',
    _type: 'sector',
    name: 'Finance',
    slug: { current: 'finance' },
    icon: 'TrendingUp',
    description: 'Financial advisory, accounting, tax preparation, and insurance services.',
    order: 8,
  },
]

// Helper to grab a sector by name
function sector(name: string): Sector {
  return mockSectors.find((s) => s.name === name)!
}

// ─── Members ────────────────────────────────────────────────────────────────

const mockImage = {
  _type: 'image' as const,
  asset: { _ref: 'image-placeholder', _type: 'reference' as const },
}

export const mockMembers: Member[] = [
  {
    _id: 'member-1',
    _type: 'member',
    name: 'Raj Patel',
    slug: { current: 'raj-patel' },
    businessName: 'Patel Medical Group',
    sector: sector('Healthcare'),
    city: 'Fresno',
    bio: 'Board-certified physician with over 20 years of experience serving the Central Valley community. Founded Patel Medical Group in 2008 to provide comprehensive family healthcare.',
    photo: mockImage,
    website: 'https://patelmedicalgroupfresno.com',
    linkedin: 'https://linkedin.com/in/rajpatel',
    phone: '(559) 555-0101',
    email: 'raj@patelmedicalgroupfresno.com',
    isMentor: true,
    mentorExpertise: ['Healthcare Management', 'Practice Growth', 'Staff Retention'],
    featured: true,
    memberSince: '2012-03-15',
    order: 1,
  },
  {
    _id: 'member-2',
    _type: 'member',
    name: 'Priya Sharma',
    slug: { current: 'priya-sharma' },
    businessName: 'Sharma Legal Associates',
    sector: sector('Legal'),
    city: 'Clovis',
    bio: 'Immigration and business law attorney helping families and entrepreneurs navigate the legal system. Active advocate for small business rights in the Valley.',
    photo: mockImage,
    website: 'https://sharmalegalclovis.com',
    linkedin: 'https://linkedin.com/in/priyasharma',
    phone: '(559) 555-0102',
    email: 'priya@sharmalegalclovis.com',
    isMentor: true,
    mentorExpertise: ['Immigration Law', 'Business Formation', 'Contracts'],
    featured: true,
    memberSince: '2013-06-01',
    order: 2,
  },
  {
    _id: 'member-3',
    _type: 'member',
    name: 'Vikram Mehta',
    slug: { current: 'vikram-mehta' },
    businessName: 'Valley Tech Solutions',
    sector: sector('Technology'),
    city: 'Fresno',
    bio: 'Full-stack software engineer turned entrepreneur. Valley Tech Solutions provides custom web and mobile applications for small businesses throughout the Central Valley.',
    photo: mockImage,
    website: 'https://valleytechsolutions.com',
    linkedin: 'https://linkedin.com/in/vikrammehta',
    phone: '(559) 555-0103',
    email: 'vikram@valleytechsolutions.com',
    isMentor: false,
    mentorExpertise: [],
    featured: true,
    memberSince: '2016-01-10',
    order: 3,
  },
  {
    _id: 'member-4',
    _type: 'member',
    name: 'Anita Desai',
    slug: { current: 'anita-desai' },
    businessName: 'Desai Realty Group',
    sector: sector('Real Estate'),
    city: 'Fresno',
    bio: 'Top-producing real estate broker specializing in commercial properties and multi-family investments across the Central Valley market.',
    photo: mockImage,
    linkedin: 'https://linkedin.com/in/anitadesai',
    phone: '(559) 555-0104',
    email: 'anita@desairealtygroup.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2014-09-20',
    order: 4,
  },
  {
    _id: 'member-5',
    _type: 'member',
    name: 'Suresh Gupta',
    slug: { current: 'suresh-gupta' },
    businessName: 'Gupta Hospitality Inc.',
    sector: sector('Hospitality'),
    city: 'Visalia',
    bio: 'Owner and operator of three hotels in the Visalia area. Passionate about delivering exceptional guest experiences and mentoring aspiring hoteliers.',
    photo: mockImage,
    website: 'https://guptahospitality.com',
    phone: '(559) 555-0105',
    email: 'suresh@guptahospitality.com',
    isMentor: true,
    mentorExpertise: ['Hotel Operations', 'Revenue Management', 'Franchise Development'],
    featured: false,
    memberSince: '2011-07-04',
    order: 5,
  },
  {
    _id: 'member-6',
    _type: 'member',
    name: 'Neha Kapoor',
    slug: { current: 'neha-kapoor' },
    businessName: 'Kapoor Financial Advisors',
    sector: sector('Finance'),
    city: 'Clovis',
    bio: 'Certified Financial Planner providing wealth management, retirement planning, and tax strategy services to families and business owners.',
    photo: mockImage,
    website: 'https://kapoorfinancial.com',
    linkedin: 'https://linkedin.com/in/nehakapoor',
    phone: '(559) 555-0106',
    email: 'neha@kapoorfinancial.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2017-02-14',
    order: 6,
  },
  {
    _id: 'member-7',
    _type: 'member',
    name: 'Arjun Reddy',
    slug: { current: 'arjun-reddy' },
    businessName: 'Reddy Farms LLC',
    sector: sector('Agriculture'),
    city: 'Visalia',
    bio: 'Third-generation farmer managing 500 acres of almonds and pistachios. Advocate for sustainable farming practices and agricultural innovation.',
    photo: mockImage,
    phone: '(559) 555-0107',
    email: 'arjun@reddyfarms.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2015-11-30',
    order: 7,
  },
  {
    _id: 'member-8',
    _type: 'member',
    name: 'Kavita Joshi',
    slug: { current: 'kavita-joshi' },
    businessName: 'Bright Minds Academy',
    sector: sector('Education'),
    city: 'Fresno',
    bio: 'Founded Bright Minds Academy to provide STEM education and SAT/ACT prep courses. Committed to helping Central Valley students reach top universities.',
    photo: mockImage,
    website: 'https://brightmindsacademy.com',
    linkedin: 'https://linkedin.com/in/kavitajoshi',
    phone: '(559) 555-0108',
    email: 'kavita@brightmindsacademy.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2018-08-15',
    order: 8,
  },
  {
    _id: 'member-9',
    _type: 'member',
    name: 'Deepak Nair',
    slug: { current: 'deepak-nair' },
    businessName: 'Nair Dental Care',
    sector: sector('Healthcare'),
    city: 'Clovis',
    bio: 'General and cosmetic dentist serving families in the Clovis area. Known for patient-centered care and cutting-edge dental technology.',
    photo: mockImage,
    website: 'https://nairdentalcare.com',
    phone: '(559) 555-0109',
    email: 'deepak@nairdentalcare.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2019-04-01',
    order: 9,
  },
  {
    _id: 'member-10',
    _type: 'member',
    name: 'Meera Iyer',
    slug: { current: 'meera-iyer' },
    businessName: 'Iyer & Associates CPA',
    sector: sector('Finance'),
    city: 'Fresno',
    bio: 'Certified Public Accountant specializing in small business tax planning and bookkeeping. Helps entrepreneurs keep more of what they earn.',
    photo: mockImage,
    linkedin: 'https://linkedin.com/in/meeraiyer',
    phone: '(559) 555-0110',
    email: 'meera@iyercpa.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2020-01-20',
    order: 10,
  },
  {
    _id: 'member-11',
    _type: 'member',
    name: 'Sanjay Bhatt',
    slug: { current: 'sanjay-bhatt' },
    businessName: 'Bhatt Construction & Development',
    sector: sector('Real Estate'),
    city: 'Fresno',
    bio: 'Licensed general contractor and developer focused on mixed-use and residential projects in downtown Fresno and surrounding communities.',
    photo: mockImage,
    website: 'https://bhattconstruction.com',
    phone: '(559) 555-0111',
    email: 'sanjay@bhattconstruction.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2016-05-12',
    order: 11,
  },
  {
    _id: 'member-12',
    _type: 'member',
    name: 'Ritu Malhotra',
    slug: { current: 'ritu-malhotra' },
    businessName: 'Spice Route Restaurant',
    sector: sector('Hospitality'),
    city: 'Fresno',
    bio: 'Award-winning restaurateur bringing authentic Indian cuisine to Fresno. Spice Route has been a local favorite since 2017 with a focus on farm-to-table ingredients.',
    photo: mockImage,
    website: 'https://spiceroutefresno.com',
    phone: '(559) 555-0112',
    email: 'ritu@spiceroutefresno.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2017-10-08',
    order: 12,
  },
]

// ─── Events ─────────────────────────────────────────────────────────────────

function eventDesc(text: string) {
  return [
    {
      _type: 'block' as const,
      _key: `eb-${text.slice(0, 8)}`,
      children: [{ _type: 'span' as const, _key: `es-${text.slice(0, 8)}`, text, marks: [] }],
      markDefs: [],
      style: 'normal' as const,
    },
  ]
}

export const mockEvents: Event[] = [
  {
    _id: 'event-1',
    _type: 'event',
    title: 'Annual Business Excellence Awards Gala',
    slug: { current: 'business-excellence-gala-2026' },
    date: '2026-06-14T18:00:00Z',
    endDate: '2026-06-14T22:00:00Z',
    location: 'The Grand at 1401',
    address: '1401 Fulton St, Fresno, CA 93721',
    isOnline: false,
    type: 'Gala',
    description: eventDesc('Join us for an elegant evening celebrating the achievements of Indian-American business leaders in the Central Valley. Featuring keynote speakers, awards for Business of the Year, Emerging Entrepreneur, and Community Impact, followed by dinner and networking. Black tie optional.'),
    image: mockImage,
    isMembersOnly: false,
    featured: true,
  },
  {
    _id: 'event-2',
    _type: 'event',
    title: 'Quarterly Networking Mixer',
    slug: { current: 'q2-networking-mixer' },
    date: '2026-05-10T17:30:00Z',
    endDate: '2026-05-10T20:00:00Z',
    location: 'Spice Route Restaurant',
    address: '2045 Kern St, Fresno, CA 93721',
    isOnline: false,
    type: 'Networking',
    description: eventDesc('Our signature quarterly mixer brings together business owners, professionals, and aspiring entrepreneurs for an evening of meaningful connections. Light appetizers and refreshments provided. Bring your business cards and an open mind.'),
    image: mockImage,
    isMembersOnly: false,
    featured: false,
  },
  {
    _id: 'event-3',
    _type: 'event',
    title: 'Small Business Tax Strategy Webinar',
    slug: { current: 'tax-strategy-webinar' },
    date: '2026-05-21T12:00:00Z',
    endDate: '2026-05-21T13:30:00Z',
    location: 'Online — Zoom',
    isOnline: true,
    type: 'Seminar',
    description: eventDesc('CPA Ramesh Kulkarni hosts a practical session on tax planning strategies for small business owners. Topics include quarterly estimated taxes, deduction optimization, retirement account strategies, and new 2026 tax law changes. Q&A session included.'),
    image: mockImage,
    isMembersOnly: false,
    featured: false,
  },
  {
    _id: 'event-4',
    _type: 'event',
    title: 'Vaisakhi Business Breakfast',
    slug: { current: 'vaisakhi-business-breakfast-2026' },
    date: '2026-04-13T08:00:00Z',
    endDate: '2026-04-13T10:30:00Z',
    location: 'DoubleTree by Hilton Fresno Convention Center',
    address: '2233 Ventura St, Fresno, CA 93721',
    isOnline: false,
    type: 'Networking',
    description: eventDesc('A festive morning celebrating Vaisakhi with fellow business owners. Enjoy a traditional Punjabi breakfast, hear from local leaders on the state of Indian-American business in the Valley, and connect with peers across all eight industry sectors.'),
    image: mockImage,
    isMembersOnly: false,
    featured: false,
  },
  {
    _id: 'event-5',
    _type: 'event',
    title: 'Diwali Networking Gala 2025',
    slug: { current: 'diwali-gala-2025' },
    date: '2025-11-01T18:00:00Z',
    endDate: '2025-11-01T22:00:00Z',
    location: 'Fresno Convention Center',
    address: '848 M St, Fresno, CA 93721',
    isOnline: false,
    type: 'Gala',
    description: eventDesc('Our signature annual Diwali celebration brought together over 200 guests for an evening of cultural performances, dinner, and networking. Thank you to all sponsors and attendees who made this event a landmark success.'),
    image: mockImage,
    isMembersOnly: false,
    featured: false,
  },
  {
    _id: 'event-6',
    _type: 'event',
    title: 'Digital Marketing for Small Business Workshop',
    slug: { current: 'digital-marketing-workshop' },
    date: '2026-02-15T10:00:00Z',
    endDate: '2026-02-15T14:00:00Z',
    location: 'Fresno State Lyles College of Engineering',
    address: '2320 E San Ramon Ave, Fresno, CA 93740',
    isOnline: false,
    type: 'Workshop',
    description: eventDesc('A hands-on half-day workshop covering Google Business Profile optimization, social media strategy, email marketing, and online reputation management. Attendees received personalized audits of their current digital presence. Over 60 business owners attended.'),
    image: mockImage,
    isMembersOnly: false,
    featured: false,
  },
]

// ─── Leadership ─────────────────────────────────────────────────────────────

function leaderBio(text: string) {
  return [
    {
      _type: 'block' as const,
      _key: `lb-${text.slice(0, 8)}`,
      children: [{ _type: 'span' as const, _key: `ls-${text.slice(0, 8)}`, text, marks: [] }],
      markDefs: [],
      style: 'normal' as const,
    },
  ]
}

export const mockLeadership: Leadership[] = [
  {
    _id: 'leader-1',
    _type: 'leadership',
    name: 'Sonia Heer',
    role: 'Chairwoman · Founder · Spokeswoman',
    sector: sector('Real Estate'),
    bio: leaderBio('Sonia Heer is a dynamic entrepreneur and Broker/Owner of Golden State Realty, Founder of Lavish Eventz and Fresno\'s annual Teeyan Festival, and host of the Rise with Sonia podcast. As Chairwoman and Founder of CVICC, she is dedicated to fostering business growth, cultural connections, and community engagement throughout the Central Valley.'),
    photo: mockImage,
    order: 1,
  },
  {
    _id: 'leader-2',
    _type: 'leadership',
    name: 'Dr. Surdeep Singh',
    role: 'President · Founder',
    sector: sector('Healthcare'),
    bio: leaderBio('Dr. Surdeep Singh, DDS, is the President and co-founder of CVICC. He is the youngest robotic dental practice owner in the U.S. and his Clovis-based Robotic Dental Implant Center has received recognition from the California Senate and State Assembly.'),
    photo: mockImage,
    order: 2,
  },
  {
    _id: 'leader-3',
    _type: 'leadership',
    name: 'Rajinder Kumar',
    role: 'Executive Director · Founder · Financial Advisor',
    sector: sector('Finance'),
    bio: leaderBio('Rajinder Kumar, CPFA, CRPC, SE-AWMA, Financial Advisor, is a founding member of CVICC and a Financial Advisor at Merrill Lynch in Fresno. He specializes in personalized wealth planning, helping clients pursue education funding, retirement, and long-term financial goals.'),
    photo: mockImage,
    order: 3,
  },
  {
    _id: 'leader-4',
    _type: 'leadership',
    name: 'Isha Lochab',
    role: 'Board Member',
    bio: leaderBio('Isha Lochab serves on the CVICC Board of Directors, bringing fresh perspective and energy to the chamber\'s initiatives.'),
    photo: mockImage,
    order: 4,
  },
  {
    _id: 'leader-5',
    _type: 'leadership',
    name: 'Kiran Hundal',
    role: 'Treasurer & Chief Financial Officer',
    bio: leaderBio('Kiran Hundal serves as Treasurer & Chief Financial Officer of CVICC, overseeing the chamber\'s financial operations, budget planning, and fiscal reporting. Her attention to detail and financial acumen ensure every resource is directed toward member empowerment and community growth.'),
    photo: mockImage,
    order: 5,
  },
  {
    _id: 'leader-6',
    _type: 'leadership',
    name: 'Roken Bhatt',
    role: 'Board Member · CPA',
    sector: sector('Finance'),
    bio: leaderBio('Roken Bhatt is a Certified Public Accountant and CVICC Board Member. He provides financial expertise to the chamber and helps member businesses with tax strategy, compliance, and accounting best practices through workshops and one-on-one mentorship.'),
    photo: mockImage,
    order: 6,
  },
  {
    _id: 'leader-7',
    _type: 'leadership',
    name: 'Manreet Sandhu',
    role: 'Board Member',
    bio: leaderBio('Manreet Sandhu is an active CVICC Board Member committed to strengthening the Indian-American business network in the Central Valley. She focuses on community engagement and building partnerships that create lasting impact for members.'),
    photo: mockImage,
    order: 7,
  },
  {
    _id: 'leader-8',
    _type: 'leadership',
    name: 'Akash Singal',
    role: 'Board Member',
    bio: leaderBio('Akash Singal brings entrepreneurial drive and innovative thinking to the CVICC Board. He is passionate about supporting emerging business owners and leveraging technology to help the chamber and its members thrive in a competitive marketplace.'),
    photo: mockImage,
    order: 8,
  },
]

// ─── Partners ───────────────────────────────────────────────────────────────

export const mockPartners: Partner[] = [
  {
    _id: 'partner-1',
    _type: 'partner',
    name: 'Valley Republic Bank',
    logo: mockImage,
    website: 'https://valleyrepublicbank.com',
    tier: 'Gold',
    description: 'Premier banking partner providing small business loans and financial services to CVICC members.',
    order: 1,
  },
  {
    _id: 'partner-2',
    _type: 'partner',
    name: 'Central Valley Health Network',
    logo: mockImage,
    website: 'https://cvhealthnetwork.org',
    tier: 'Gold',
    description: 'Leading healthcare network connecting providers and patients across the Central Valley.',
    order: 2,
  },
  {
    _id: 'partner-3',
    _type: 'partner',
    name: 'Fresno Area Hispanic Foundation',
    logo: mockImage,
    website: 'https://fahf.org',
    tier: 'Silver',
    description: 'Community partner promoting cross-cultural business collaboration in Fresno.',
    order: 3,
  },
  {
    _id: 'partner-4',
    _type: 'partner',
    name: 'San Joaquin Valley Manufacturing Alliance',
    logo: mockImage,
    website: 'https://sjvma.org',
    tier: 'Silver',
    description: 'Regional manufacturing alliance supporting workforce development and industry growth.',
    order: 4,
  },
  {
    _id: 'partner-5',
    _type: 'partner',
    name: 'Fresno State Lyles College of Engineering',
    logo: mockImage,
    website: 'https://fresnostate.edu/engineering',
    tier: 'Community',
    description: 'Academic partner supporting STEM education and internship opportunities for aspiring engineers.',
    order: 5,
  },
  {
    _id: 'partner-6',
    _type: 'partner',
    name: 'Downtown Fresno Partnership',
    logo: mockImage,
    website: 'https://downtownfresno.org',
    tier: 'Community',
    description: 'Revitalizing downtown Fresno and supporting small business owners in the city core.',
    order: 6,
  },
]

// ─── Site Settings ──────────────────────────────────────────────────────────

export const mockSiteSettings: SiteSettings = {
  _id: 'siteSettings',
  _type: 'siteSettings',
  memberCount: 100,
  sectorCount: 8,
  eventsPerYear: 20,
  countiesServed: 6,
  heroHeadline: 'Building Indian Business Leadership in the Valley',
  heroSubtext:
    'The Central Valley Indian Chamber of Commerce connects, supports, and elevates Indian-American businesses across the region through networking, mentorship, and advocacy.',
  address: '4610 W Jacquelyn Ave, Fresno, CA 93722',
  phone: '(510) 453-1248',
  email: 'info@indianchamberofcommerce.org',
  instagramHandle: '@indianchamberofcommerce',
  linkedinUrl: '',
  facebookUrl: '',
  whatsappNumber: '',
  tallyMembershipFormId: 'mRxVYa',
  tallyContactFormId: 'wQ7yBn',
}
