import type {
  Sector,
  Member,
  Event,
  Leadership,
  Partner,
  SiteSettings,
} from './types'

// ─── Sectors ────────────────────────────────────────────────────────────────

export const mockSectors: Sector[] = [
  {
    _id: 'sector-1',
    _type: 'sector',
    name: 'Healthcare',
    slug: { current: 'healthcare' },
    icon: 'Stethoscope',
    description: 'Medical practices, clinics, pharmacies, and healthcare technology providers serving the Central Valley.',
    order: 1,
  },
  {
    _id: 'sector-2',
    _type: 'sector',
    name: 'Real Estate',
    slug: { current: 'real-estate' },
    icon: 'Building2',
    description: 'Residential and commercial real estate developers, brokers, and property management firms.',
    order: 2,
  },
  {
    _id: 'sector-3',
    _type: 'sector',
    name: 'Legal',
    slug: { current: 'legal' },
    icon: 'Scale',
    description: 'Law firms and legal professionals specializing in immigration, business, and family law.',
    order: 3,
  },
  {
    _id: 'sector-4',
    _type: 'sector',
    name: 'Technology',
    slug: { current: 'technology' },
    icon: 'Code2',
    description: 'Software development, IT consulting, and technology solutions for businesses of all sizes.',
    order: 4,
  },
  {
    _id: 'sector-5',
    _type: 'sector',
    name: 'Hospitality',
    slug: { current: 'hospitality' },
    icon: 'UtensilsCrossed',
    description: 'Hotels, restaurants, catering services, and event venues across the Valley.',
    order: 5,
  },
  {
    _id: 'sector-6',
    _type: 'sector',
    name: 'Agriculture',
    slug: { current: 'agriculture' },
    icon: 'Wheat',
    description: 'Farming operations, food processing, agricultural technology, and supply chain management.',
    order: 6,
  },
  {
    _id: 'sector-7',
    _type: 'sector',
    name: 'Education',
    slug: { current: 'education' },
    icon: 'GraduationCap',
    description: 'Tutoring centers, test preparation, educational technology, and training academies.',
    order: 7,
  },
  {
    _id: 'sector-8',
    _type: 'sector',
    name: 'Finance',
    slug: { current: 'finance' },
    icon: 'TrendingUp',
    description: 'Financial advisory, accounting, tax preparation, and insurance services.',
    order: 8,
  },
]

// Helper to grab a sector by name
function sector(name: string): Sector {
  return mockSectors.find((s) => s.name === name)!
}

// ─── Members ────────────────────────────────────────────────────────────────

const mockImage = {
  _type: 'image' as const,
  asset: { _ref: 'image-placeholder', _type: 'reference' as const },
}

export const mockMembers: Member[] = [
  {
    _id: 'member-1',
    _type: 'member',
    name: 'Raj Patel',
    slug: { current: 'raj-patel' },
    businessName: 'Patel Medical Group',
    sector: sector('Healthcare'),
    city: 'Fresno',
    bio: 'Board-certified physician with over 20 years of experience serving the Central Valley community. Founded Patel Medical Group in 2008 to provide comprehensive family healthcare.',
    photo: mockImage,
    website: 'https://patelmedicalgroupfresno.com',
    linkedin: 'https://linkedin.com/in/rajpatel',
    phone: '(559) 555-0101',
    email: 'raj@patelmedicalgroupfresno.com',
    isMentor: true,
    mentorExpertise: ['Healthcare Management', 'Practice Growth', 'Staff Retention'],
    featured: true,
    memberSince: '2012-03-15',
    order: 1,
  },
  {
    _id: 'member-2',
    _type: 'member',
    name: 'Priya Sharma',
    slug: { current: 'priya-sharma' },
    businessName: 'Sharma Legal Associates',
    sector: sector('Legal'),
    city: 'Clovis',
    bio: 'Immigration and business law attorney helping families and entrepreneurs navigate the legal system. Active advocate for small business rights in the Valley.',
    photo: mockImage,
    website: 'https://sharmalegalclovis.com',
    linkedin: 'https://linkedin.com/in/priyasharma',
    phone: '(559) 555-0102',
    email: 'priya@sharmalegalclovis.com',
    isMentor: true,
    mentorExpertise: ['Immigration Law', 'Business Formation', 'Contracts'],
    featured: true,
    memberSince: '2013-06-01',
    order: 2,
  },
  {
    _id: 'member-3',
    _type: 'member',
    name: 'Vikram Mehta',
    slug: { current: 'vikram-mehta' },
    businessName: 'Valley Tech Solutions',
    sector: sector('Technology'),
    city: 'Fresno',
    bio: 'Full-stack software engineer turned entrepreneur. Valley Tech Solutions provides custom web and mobile applications for small businesses throughout the Central Valley.',
    photo: mockImage,
    website: 'https://valleytechsolutions.com',
    linkedin: 'https://linkedin.com/in/vikrammehta',
    phone: '(559) 555-0103',
    email: 'vikram@valleytechsolutions.com',
    isMentor: false,
    mentorExpertise: [],
    featured: true,
    memberSince: '2016-01-10',
    order: 3,
  },
  {
    _id: 'member-4',
    _type: 'member',
    name: 'Anita Desai',
    slug: { current: 'anita-desai' },
    businessName: 'Desai Realty Group',
    sector: sector('Real Estate'),
    city: 'Fresno',
    bio: 'Top-producing real estate broker specializing in commercial properties and multi-family investments across the Central Valley market.',
    photo: mockImage,
    linkedin: 'https://linkedin.com/in/anitadesai',
    phone: '(559) 555-0104',
    email: 'anita@desairealtygroup.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2014-09-20',
    order: 4,
  },
  {
    _id: 'member-5',
    _type: 'member',
    name: 'Suresh Gupta',
    slug: { current: 'suresh-gupta' },
    businessName: 'Gupta Hospitality Inc.',
    sector: sector('Hospitality'),
    city: 'Visalia',
    bio: 'Owner and operator of three hotels in the Visalia area. Passionate about delivering exceptional guest experiences and mentoring aspiring hoteliers.',
    photo: mockImage,
    website: 'https://guptahospitality.com',
    phone: '(559) 555-0105',
    email: 'suresh@guptahospitality.com',
    isMentor: true,
    mentorExpertise: ['Hotel Operations', 'Revenue Management', 'Franchise Development'],
    featured: false,
    memberSince: '2011-07-04',
    order: 5,
  },
  {
    _id: 'member-6',
    _type: 'member',
    name: 'Neha Kapoor',
    slug: { current: 'neha-kapoor' },
    businessName: 'Kapoor Financial Advisors',
    sector: sector('Finance'),
    city: 'Clovis',
    bio: 'Certified Financial Planner providing wealth management, retirement planning, and tax strategy services to families and business owners.',
    photo: mockImage,
    website: 'https://kapoorfinancial.com',
    linkedin: 'https://linkedin.com/in/nehakapoor',
    phone: '(559) 555-0106',
    email: 'neha@kapoorfinancial.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2017-02-14',
    order: 6,
  },
  {
    _id: 'member-7',
    _type: 'member',
    name: 'Arjun Reddy',
    slug: { current: 'arjun-reddy' },
    businessName: 'Reddy Farms LLC',
    sector: sector('Agriculture'),
    city: 'Visalia',
    bio: 'Third-generation farmer managing 500 acres of almonds and pistachios. Advocate for sustainable farming practices and agricultural innovation.',
    photo: mockImage,
    phone: '(559) 555-0107',
    email: 'arjun@reddyfarms.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2015-11-30',
    order: 7,
  },
  {
    _id: 'member-8',
    _type: 'member',
    name: 'Kavita Joshi',
    slug: { current: 'kavita-joshi' },
    businessName: 'Bright Minds Academy',
    sector: sector('Education'),
    city: 'Fresno',
    bio: 'Founded Bright Minds Academy to provide STEM education and SAT/ACT prep courses. Committed to helping Central Valley students reach top universities.',
    photo: mockImage,
    website: 'https://brightmindsacademy.com',
    linkedin: 'https://linkedin.com/in/kavitajoshi',
    phone: '(559) 555-0108',
    email: 'kavita@brightmindsacademy.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2018-08-15',
    order: 8,
  },
  {
    _id: 'member-9',
    _type: 'member',
    name: 'Deepak Nair',
    slug: { current: 'deepak-nair' },
    businessName: 'Nair Dental Care',
    sector: sector('Healthcare'),
    city: 'Clovis',
    bio: 'General and cosmetic dentist serving families in the Clovis area. Known for patient-centered care and cutting-edge dental technology.',
    photo: mockImage,
    website: 'https://nairdentalcare.com',
    phone: '(559) 555-0109',
    email: 'deepak@nairdentalcare.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2019-04-01',
    order: 9,
  },
  {
    _id: 'member-10',
    _type: 'member',
    name: 'Meera Iyer',
    slug: { current: 'meera-iyer' },
    businessName: 'Iyer & Associates CPA',
    sector: sector('Finance'),
    city: 'Fresno',
    bio: 'Certified Public Accountant specializing in small business tax planning and bookkeeping. Helps entrepreneurs keep more of what they earn.',
    photo: mockImage,
    linkedin: 'https://linkedin.com/in/meeraiyer',
    phone: '(559) 555-0110',
    email: 'meera@iyercpa.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2020-01-20',
    order: 10,
  },
  {
    _id: 'member-11',
    _type: 'member',
    name: 'Sanjay Bhatt',
    slug: { current: 'sanjay-bhatt' },
    businessName: 'Bhatt Construction & Development',
    sector: sector('Real Estate'),
    city: 'Fresno',
    bio: 'Licensed general contractor and developer focused on mixed-use and residential projects in downtown Fresno and surrounding communities.',
    photo: mockImage,
    website: 'https://bhattconstruction.com',
    phone: '(559) 555-0111',
    email: 'sanjay@bhattconstruction.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2016-05-12',
    order: 11,
  },
  {
    _id: 'member-12',
    _type: 'member',
    name: 'Ritu Malhotra',
    slug: { current: 'ritu-malhotra' },
    businessName: 'Spice Route Restaurant',
    sector: sector('Hospitality'),
    city: 'Fresno',
    bio: 'Award-winning restaurateur bringing authentic Indian cuisine to Fresno. Spice Route has been a local favorite since 2017 with a focus on farm-to-table ingredients.',
    photo: mockImage,
    website: 'https://spiceroutefresno.com',
    phone: '(559) 555-0112',
    email: 'ritu@spiceroutefresno.com',
    isMentor: false,
    mentorExpertise: [],
    featured: false,
    memberSince: '2017-10-08',
    order: 12,
  },
]

// ─── Events ─────────────────────────────────────────────────────────────────

export const mockEvents: Event[] = [
  // Upcoming events
  {
    _id: 'event-1',
    _type: 'event',
    title: 'Event 1',
    slug: { current: 'event-1' },
    date: '2026-04-18T18:00:00Z',
    endDate: '2026-04-18T22:00:00Z',
    location: 'Venue TBD',
    address: 'Fresno, CA',
    isOnline: false,
    type: 'Networking',
    description: [
      {
        _type: 'block',
        _key: 'b1',
        children: [
          {
            _type: 'span',
            _key: 's1',
            text: 'Details coming soon. Stay tuned for more information about this upcoming event.',
            marks: [],
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    image: mockImage,
    isMembersOnly: false,
    featured: true,
  },
  {
    _id: 'event-2',
    _type: 'event',
    title: 'Event 2',
    slug: { current: 'event-2' },
    date: '2026-05-03T10:00:00Z',
    endDate: '2026-05-03T12:00:00Z',
    location: 'Venue TBD',
    address: 'Fresno, CA',
    isOnline: false,
    type: 'Networking',
    description: [
      {
        _type: 'block',
        _key: 'b2',
        children: [
          {
            _type: 'span',
            _key: 's2',
            text: 'Details coming soon. Stay tuned for more information about this upcoming event.',
            marks: [],
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    image: mockImage,
    isMembersOnly: false,
    featured: false,
  },
  {
    _id: 'event-3',
    _type: 'event',
    title: 'Event 3',
    slug: { current: 'event-3' },
    date: '2026-05-21T14:00:00Z',
    endDate: '2026-05-21T16:00:00Z',
    location: 'Online',
    isOnline: true,
    type: 'Seminar',
    description: [
      {
        _type: 'block',
        _key: 'b3',
        children: [
          {
            _type: 'span',
            _key: 's3',
            text: 'Details coming soon. Stay tuned for more information about this upcoming event.',
            marks: [],
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    image: mockImage,
    isMembersOnly: false,
    featured: false,
  },
  // Past events
  {
    _id: 'event-4',
    _type: 'event',
    title: 'Event 4',
    slug: { current: 'event-4' },
    date: '2026-01-18T17:30:00Z',
    endDate: '2026-01-18T20:00:00Z',
    location: 'Venue TBD',
    address: 'Fresno, CA',
    isOnline: false,
    type: 'Networking',
    description: [
      {
        _type: 'block',
        _key: 'b4',
        children: [
          {
            _type: 'span',
            _key: 's4',
            text: 'This event has concluded. Thank you to all who attended.',
            marks: [],
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    image: mockImage,
    isMembersOnly: false,
    featured: false,
  },
  {
    _id: 'event-5',
    _type: 'event',
    title: 'Event 5',
    slug: { current: 'event-5' },
    date: '2026-02-08T09:00:00Z',
    endDate: '2026-02-08T13:00:00Z',
    location: 'Venue TBD',
    address: 'Fresno, CA',
    isOnline: false,
    type: 'Networking',
    description: [
      {
        _type: 'block',
        _key: 'b5',
        children: [
          {
            _type: 'span',
            _key: 's5',
            text: 'This event has concluded. Thank you to all who attended.',
            marks: [],
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    image: mockImage,
    isMembersOnly: false,
    featured: false,
  },
  {
    _id: 'event-6',
    _type: 'event',
    title: 'Event 6',
    slug: { current: 'event-6' },
    date: '2025-10-25T18:00:00Z',
    endDate: '2025-10-25T22:00:00Z',
    location: 'Venue TBD',
    address: 'Fresno, CA',
    isOnline: false,
    type: 'Networking',
    description: [
      {
        _type: 'block',
        _key: 'b6',
        children: [
          {
            _type: 'span',
            _key: 's6',
            text: 'This event has concluded. Thank you to all who attended.',
            marks: [],
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    image: mockImage,
    isMembersOnly: false,
    featured: false,
  },
]

// ─── Leadership ─────────────────────────────────────────────────────────────

export const mockLeadership: Leadership[] = [
  {
    _id: 'leader-1',
    _type: 'leadership',
    name: 'Anil Varma',
    role: 'President',
    sector: sector('Healthcare'),
    bio: [
      {
        _type: 'block',
        _key: 'lb1',
        children: [
          {
            _type: 'span',
            _key: 'ls1',
            text: 'Dr. Anil Varma has served as President of CVICC since 2022. A cardiologist by training, he is passionate about growing the Indian business community in the Central Valley and creating pathways for the next generation of entrepreneurs.',
            marks: [],
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    photo: mockImage,
    videoUrl: 'https://youtube.com/watch?v=example1',
    order: 1,
  },
  {
    _id: 'leader-2',
    _type: 'leadership',
    name: 'Sunita Rao',
    role: 'Vice President',
    sector: sector('Education'),
    bio: [
      {
        _type: 'block',
        _key: 'lb2',
        children: [
          {
            _type: 'span',
            _key: 'ls2',
            text: 'Sunita Rao is a veteran educator and founder of two tutoring centers in the Fresno area. As Vice President, she leads CVICC\'s mentorship and youth entrepreneurship initiatives.',
            marks: [],
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    photo: mockImage,
    order: 2,
  },
  {
    _id: 'leader-3',
    _type: 'leadership',
    name: 'Kiran Shah',
    role: 'Secretary',
    sector: sector('Legal'),
    bio: [
      {
        _type: 'block',
        _key: 'lb3',
        children: [
          {
            _type: 'span',
            _key: 'ls3',
            text: 'Kiran Shah is a practicing attorney specializing in corporate law. She ensures CVICC operations run smoothly and maintains strong relationships with city and county officials.',
            marks: [],
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    photo: mockImage,
    order: 3,
  },
  {
    _id: 'leader-4',
    _type: 'leadership',
    name: 'Ramesh Kulkarni',
    role: 'Treasurer',
    sector: sector('Finance'),
    bio: [
      {
        _type: 'block',
        _key: 'lb4',
        children: [
          {
            _type: 'span',
            _key: 'ls4',
            text: 'Ramesh Kulkarni brings 25 years of accounting and financial management experience. As Treasurer, he oversees CVICC\'s budget, sponsorship funds, and financial reporting.',
            marks: [],
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    photo: mockImage,
    order: 4,
  },
  {
    _id: 'leader-5',
    _type: 'leadership',
    name: 'Pooja Agarwal',
    role: 'Board Member',
    sector: sector('Technology'),
    bio: [
      {
        _type: 'block',
        _key: 'lb5',
        children: [
          {
            _type: 'span',
            _key: 'ls5',
            text: 'Pooja Agarwal is a tech entrepreneur and startup advisor. She chairs the CVICC Innovation Committee and organizes the annual Digital Marketing Seminar series.',
            marks: [],
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    photo: mockImage,
    order: 5,
  },
]

// ─── Partners ───────────────────────────────────────────────────────────────

export const mockPartners: Partner[] = [
  {
    _id: 'partner-1',
    _type: 'partner',
    name: 'Valley Republic Bank',
    logo: mockImage,
    website: 'https://valleyrepublicbank.com',
    tier: 'Gold',
    description: 'Premier banking partner providing small business loans and financial services to CVICC members.',
    order: 1,
  },
  {
    _id: 'partner-2',
    _type: 'partner',
    name: 'Central Valley Health Network',
    logo: mockImage,
    website: 'https://cvhealthnetwork.org',
    tier: 'Gold',
    description: 'Leading healthcare network connecting providers and patients across the Central Valley.',
    order: 2,
  },
  {
    _id: 'partner-3',
    _type: 'partner',
    name: 'Fresno Area Hispanic Foundation',
    logo: mockImage,
    website: 'https://fahf.org',
    tier: 'Silver',
    description: 'Community partner promoting cross-cultural business collaboration in Fresno.',
    order: 3,
  },
  {
    _id: 'partner-4',
    _type: 'partner',
    name: 'San Joaquin Valley Manufacturing Alliance',
    logo: mockImage,
    website: 'https://sjvma.org',
    tier: 'Silver',
    description: 'Regional manufacturing alliance supporting workforce development and industry growth.',
    order: 4,
  },
  {
    _id: 'partner-5',
    _type: 'partner',
    name: 'Fresno State Lyles College of Engineering',
    logo: mockImage,
    website: 'https://fresnostate.edu/engineering',
    tier: 'Community',
    description: 'Academic partner supporting STEM education and internship opportunities for aspiring engineers.',
    order: 5,
  },
  {
    _id: 'partner-6',
    _type: 'partner',
    name: 'Downtown Fresno Partnership',
    logo: mockImage,
    website: 'https://downtownfresno.org',
    tier: 'Community',
    description: 'Revitalizing downtown Fresno and supporting small business owners in the city core.',
    order: 6,
  },
]

// ─── Site Settings ──────────────────────────────────────────────────────────

export const mockSiteSettings: SiteSettings = {
  _id: 'siteSettings',
  _type: 'siteSettings',
  memberCount: 200,
  sectorCount: 12,
  eventsPerYear: 40,
  yearsEstablished: 15,
  heroHeadline: 'Building Indian Business Leadership in the Valley',
  heroSubtext:
    'The Central Valley Indian Chamber of Commerce connects, supports, and elevates Indian-American businesses across the region through networking, mentorship, and advocacy.',
  address: '123 Fulton Street, Fresno, CA 93721',
  phone: '(559) 555-0100',
  email: 'info@cvicc.org',
  instagramHandle: '@cvicc_fresno',
  linkedinUrl: 'https://linkedin.com/company/cvicc',
  facebookUrl: 'https://facebook.com/cviccindia',
  whatsappNumber: '+15595550100',
  tallyMembershipFormId: 'mRxVYa',
  tallyContactFormId: 'wQ7yBn',
}
